http:
    port: 8080
    adminPort: 8081
    connectorType: nonblocking
    requestLog:
        console:
            enabled: false
        file:
            enabled: true
            currentLogFilename: /var/log/beacon/access.log
            archive: true
            archivedLogFilenamePattern: /var/log/beacon/access-%d.log.gz
            archivedFileCount: 50

logging:
    console:
        enabled: false
    file:
        enabled: true
        currentLogFilename: /var/log/beacon/service.log
        archive: true
        archivedLogFilenamePattern: /var/log/beacon/service-%d.log.gz
        archivedFileCount: 50

mysql:
    driverClass: com.mysql.jdbc.Driver
    user: ntropy
    password: 2bc869f70e28759f57561b5303f4883c
    url: jdbc:mysql://54.235.120.143/ntropy
    maxWaitForConnection: 1s
    validationQuery: "/* MyService Health Check */ SELECT distinct 1 FROM metadata_organization"
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    checkConnectionHealthWhenIdleFor: 10s
    closeConnectionIfIdleFor: 1 minute

kafka:
    zookeeper:
        hosts:
            - REPLACE_WITH_ZOOKEEPER_SERVERS
        port: 2181
        connectionTimeout: 10s
        sessionTimeout: 10s
        namespace: "/"
    sendBufferSize: 10KB
    connectionTimeout: 5000s
    reconnectInterval: 30000
    maxMessageSize: 1MB
    compression: none
    partitionMissRetries: 3
    async:
        queueTime: 5s
        queueSize: 10000
        batchSize: 2000
    serializerClass: kafka.serializer.StringEncoder

authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m

grepdata:
    workerId: 0
    maxWorkers: 64
    zk:
        hosts:
            - REPLACE_WITH_ZOOKEEPER_SERVERS
        port: 2181
        connectionTimeout: 10s
        sessionTimeout: 10s
        namespace: "/grepdata"
    email:
        enabled: false
        host: "smtp.gmail.com"
        port: 587
        user: "alert-sender@ntropy.io"
        password: "Ntropy33"
        from: "alert-sender@ntropy.io"
        to: "alerts@grepdata.com"

